import { useEffect, useState } from "react";

import DocumentsTable from "./DocumentsTable";
import { fetchArtifactsByCase } from "../../api/artifact";

import "./DocumentsView.css";

export default function DocumentsView({
  caseId,
}) {
  const [artifacts, setArtifacts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const loadArtifacts = async () => {
    if (!caseId) {
      setArtifacts([]);
      setError(null);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const data = await fetchArtifactsByCase(caseId);

      setArtifacts(
        Array.isArray(data)
          ? data
          : data?.artifacts ?? []
      );
    } catch (err) {
      console.error("Failed to load artifacts:", err);

      setArtifacts([]);
      setError(
        err instanceof Error
          ? err.message
          : "Failed to load documents."
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadArtifacts();
  }, [caseId]);

  if (!caseId) {
    return (
      <main className="documents-view">
        <div className="documents-view-empty">
          <h2>No case selected</h2>

          <p>
            Select a case to display its documents.
          </p>
        </div>
      </main>
    );
  }

  return (
    <main className="documents-view">
      <header className="documents-view-header">
        <div>
          <p className="documents-view-eyebrow">
            Case documents
          </p>

          <h1>Documents</h1>

          <p className="documents-view-description">
            View uploaded source files, extracted text,
            editable artifact content and generated output files.
          </p>
        </div>

        <div className="documents-view-header-actions">
          <span className="documents-count">
            {artifacts.length}{" "}
            {artifacts.length === 1
              ? "document"
              : "documents"}
          </span>

          <button
            type="button"
            className="documents-refresh-button"
            onClick={loadArtifacts}
            disabled={loading}
          >
            {loading ? "Loading..." : "Refresh"}
          </button>

          <button
            type="button"
            className="documents-upload-button"
            onClick={() => {
              console.log("Upload document");
            }}
          >
            + Upload document
          </button>
        </div>
      </header>

      <section className="documents-view-content">
        {loading && artifacts.length === 0 ? (
          <div className="documents-view-status">
            <div className="documents-view-spinner" />

            <span>Loading documents...</span>
          </div>
        ) : error ? (
          <div className="documents-view-error">
            <strong>Documents could not be loaded.</strong>

            <p>{error}</p>

            <button
              type="button"
              onClick={loadArtifacts}
            >
              Try again
            </button>
          </div>
        ) : artifacts.length === 0 ? (
          <div className="documents-view-empty">
            <div className="documents-empty-icon">
              <DocumentIcon />
            </div>

            <h2>No documents available</h2>

            <p>
              Uploaded files and documents generated by the
              application will appear here.
            </p>

            <button
              type="button"
              className="documents-empty-upload-button"
              onClick={() => {
                console.log("Upload document");
              }}
            >
              Upload first document
            </button>
          </div>
        ) : (
          <DocumentsTable
            artifacts={artifacts}
            onArtifactsChange={setArtifacts}
          />
        )}
      </section>
    </main>
  );
}

function DocumentIcon() {
  return (
    <svg
      viewBox="0 0 64 64"
      aria-hidden="true"
    >
      <path d="M17 8H39L49 18V56H17Z" />

      <path d="M39 8V18H49" />

      <path d="M24 29H42" />

      <path d="M24 37H42" />

      <path d="M24 45H36" />
    </svg>
  );
}